### ISSUE TITLE
preprocess output and prediction module

### ISSUE THREAD

**Issue by savaridas** [nailo2c/deeplog#1]
Sir, Thank you for this implementation of Deeplog.
i am using this work for further research in this work.
when executing the existing code,
the preprocess output eventid results as 1145 
and once training completed, the prediction module results, precision:0, so divide by zero error.

Kindly request to support.

Svaridasan.P

**Comment by nailo2c** [comment]
Hi, I re-run `preprocess.py` and the length of `event_id_map` is still 1143. Could you provide me your command or give a screenshot?

And if your `--num-class` is less than the length of `event_id_map`, it will give an error. But if your `--num-class` is greater than the length of `event_id_map`, it will work as usual.

**Comment by savaridas** [comment]
![deeplog_event_id](https://user-images.githubusercontent.com/35776622/85944120-25bfb900-b952-11ea-8e7c-5d7e24f50751.jpeg)

the code repository is cloned from git to colab environment and followed your execution steps, as it is mentioned.

**Comment by savaridas** [comment]
[deeplog_colab_file.zip](https://github.com/nailo2c/deeplog/files/4842034/deeplog_colab_file.zip)

**Comment by nailo2c** [comment]
Hi @savaridas , thanks for your report, I already fix this issue on commit `4f57239`.

**Comment by savaridas** [comment]
Thank you for the fix Aaron Chen , 
please find the attached; snapshot execution of preprocess.py and predict.py 
still the event id length results as 1145 and
the predict output throws divide by zero error.
kindly request to provide your valuable comments. Thanking you

![image](https://user-images.githubusercontent.com/35776622/85983627-76dcb500-ba05-11ea-9047-9028e84ddcec.png)
![image](https://user-images.githubusercontent.com/35776622/85983639-7e03c300-ba05-11ea-989d-4ccc8c515c2f.png)

**Comment by nailo2c** [comment]
Hi @savaridas , I found out the reason for this issue because the `glob` function has different orders on different OS.

So I fix the order of logs, please check again, I think your issue will be solved.

Or you can check my colab, it base on your colab file.
[https://colab.research.google.com/drive/1xWHovxTkysiPei68bTywqB2oCo6JelAU?usp=sharing](https://colab.research.google.com/drive/1xWHovxTkysiPei68bTywqB2oCo6JelAU?usp=sharing)

**Comment by savaridas** [comment]
Greetings Aaron Chen,
Thank you for the update, and yes the prediction model results as per the expectation.
and when the thres value is 30, it results in better accuracy, and other metric as well. so any reason its to be 30.
Have you created any recording, to detail on your implementation?
Thank you,

**Comment by nailo2c** [comment]
Hi @savaridas , to set the threshold to 30 is much better, thanks for your reporting.

And I don't have any recording to explain my implementation. Actually I just standing upon the shoulders of giants, I reference others implement and integration them together.
