### ISSUE TITLE
The result can't be reproduced

### ISSUE THREAD

**Issue by HelenGuohx** [nailo2c/deeplog#2]
I runned the code in colab https://colab.research.google.com/drive/1xWHovxTkysiPei68bTywqB2oCo6JelAU?usp=sharing#scrollTo=f8xH9L33cWL0, twice. 
The result changed 
<img width="681" alt="Screen Shot 2020-06-29 at 6 35 23 PM" src="https://user-images.githubusercontent.com/35051874/86069525-5fb6bb00-ba37-11ea-8a81-903dc36094c9.png">
<img width="782" alt="Screen Shot 2020-06-29 at 6 35 33 PM" src="https://user-images.githubusercontent.com/35051874/86069527-604f5180-ba37-11ea-9abc-e773307f5149.png">

**Comment by nailo2c** [comment]
Hi @HelenGuohx , because the LSTM-model training is stochastic, so I add random seed, now it can reproduce the result, please try again 😃

**Comment by HelenGuohx** [comment]
Thanks. I noticed that you are using fixed window to make the sequences. but the paper [deeplog](https://www.cs.utah.edu/~lifeifei/papers/deeplog.pdf) use session window to make sequences based on instance id. Did you try session window?

**Comment by nailo2c** [comment]
No, because in my research I use other logs that are not suited for use session window. The example data is I randomly picked open data that has labeled.

Maybe you can try on the session window, perhaps it would be a better result than my example 😃
