### ISSUE TITLE
In predict.py, I do not understand why "ground_truth" for 'abnormal_has_anomaly' is  all 1.  Is there no correct or normal data in abnormal data?

### ISSUE THREAD

**Issue by lizhzh8** [nailo2c/deeplog#4]
`ground_truth = [1]*len(abnormal_has_anomaly) + [0]*len(normal_has_anomaly)
    predict = abnormal_has_anomaly + normal_has_anomaly`

![image](https://user-images.githubusercontent.com/30767119/102299698-5b9f3b00-3f8e-11eb-8252-74bf06ccad2e.png)

**Comment by nailo2c** [comment]
Hi @lizhzh8 , that's because I load the abnormal test set first, then load the normal set. And I concat them, so the ground truth set is abnormal on the head and normal on the tail.

**Comment by lizhzh8** [comment]
> Hi @lizhzh8 , that's because I load the abnormal test set first, then load the normal set. And I concat them, so the ground truth set is abnormal on the head and normal on the tail.

Hi, @nailo2c . In my opinion, there is almost normal data and only a little abnormal data  in abnormal dataset.so ground_truth is not all 1 for abnormal_has_anomaly. Is that right?Thanks

**Comment by nailo2c** [comment]
Hi @lizhzh8 , I think you're right, I should only tag VM in anomaly_labels.txt to be abnormal.
Thanks for your feedback!
